### ISSUE TITLE
Convenient installation with PyPI and conda

### ISSUE THREAD

**Issue by mehrdadbakhtiari** [mehrdadbakhtiari/adVNTR#13]
Suggested by @wdecoster

**Comment by nh13** [comment]
This is a start for the meta.yaml, but will need some work after you create a setup.py:
```
{% set version="0.0.1a" %}
{% set tag="049db44ae0770cb6d5c36201769f026ebd2f9898" %}
about:
    home: https://github.com/mehrdadbakhtiari/adVNTR
    license: BSD 3-Clause
    summary: A tool for genotyping Variable Number Tandem Repeats (VNTR) from sequence data
package:
    name: adVNTR
    version: {{ version }}
build:
  number: 0
  skip: false
source:
  fn: {{ tag }}.tar.gz
  url: https://github.com/mehrdadbakhtiari/adVNTR/archive/{{ tag }}.tar.gz
  sha256: c745e38c9a88011a020e5a78fc23e84d922b7c6da756ce20a78ea3d2e0ab97f3
requirements:
  build:
    - python
  run:
    - python
    - muscle
    - pysam=0.9.1.4
    - biopython
    - cython 
    - networkx 
    - scipy 
    - joblib 
    - blast
    - htslib==1.3
    - networkx==1.11
```

**Comment by druvus** [comment]
@mehrdadbakhtiari I am happy to help you adding adVNTR to Bioconda once you have a setup.py-based installation. @nh13 gave you nice skeleton to modify but I would also recommend you to tag a release instead of using commit id.

**Comment by nh13** [comment]
Agreed, but there were no tags when I wrote it ;)

I'd also update the build section with a setup.py and a main method:
```
build:
  number: 0
  skip: false
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - advntr=advntr.__main__:main
```
